baseURL: "https://www.zinzolin.fr"
canonifyURLs: true
copyright: "Anthony <nobr>Nelzin-Santos</nobr> — Tous droits réservés"
defaultContentLanguage: "fr"
disableHugoGeneratorInject: true
languageCode: "fr"
markup:
  goldmark:
    renderer:
      unsafe: true
theme: "zinzolin"
timeZone: "Europe/Paris"
timeout: 60s
title: "Zinzolin"